LOG_DIR = 'LOG_DIR'
LOG_LEVEL = 'LOG_LEVEL'
TITLE = 'TITLE'
PORT = 'PORT'
API_KEY = 'API_KEY'
API_SERVER = 'API_SERVER'
WS_SERVER = 'WS_SERVER'
AGENT_ID = 'AGENT_ID'
TEMPLATES_DIR = 'TEMPLATES_DIR'

# DB (Server / Postgres)
PG_HOST = 'PG_HOST'
PG_PORT = 'PG_PORT'
PG_DB = 'PG_DB'
PG_USER = 'PG_USER'
PG_PASSWORD = 'PG_PASSWORD'

# DB (Agent / SQLite)
SQLITE_PATH = 'SQLITE_PATH'

# Users
ADMIN_EMAIL = 'ADMIN_EMAIL'
ADMIN_INIT_PASSWORD = 'ADMIN_INIT_PASSWORD'
ADMIN_INIT_API_KEY = 'ADMIN_INIT_API_KEY'